import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import { Job, fetchJobs } from '../src/helpers'
import { useRouter } from 'next/router'

// https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

export default function Sample(props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { locale } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>SSG page</h1>
        <ul>
          {props.jobs.map((job: Job) => {
            return (
              <li key={job.id}>
                <Link href={`/${locale}/jobs/${job.id}`} locale={false}>{job.title}</Link>
              </li>
            );
          })}
        </ul>
        <p className={styles.description}>
          <Link href="/sample_isr">Go to Sample Incremental Static Regeneration page</Link>
        </p>
        <p className={styles.description}>
          <Link href="/sample_ssr">Go to Sample Server Side Renderder page</Link>
        </p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const data = await fetchJobs();

  if (!data) {
    return {
      notFound: true,
    }
  }

  const jobs: Job[] = data.results.map((result: Job) => {
    return {
      id: result.id,
      title: result.title,
      url: result.url,
      slug: result.slug
    }
  })

  return {
    props: { jobs }, // will be passed to the page component as props
  }
}
