import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import { Job, fetchJobs } from '../src/helpers'

// https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

export default function Sample({ jobs }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>ISR page</h1>
        <ul>
          {jobs.map((job: Job) => {
            return (
              <li key={job.id}>
                <a href={job.url}>{job.title}</a>
              </li>
            );
          })}
        </ul>
        <p className={styles.description}>
          <Link href="/sample_ssg">Go to Sample Static Site Generated page</Link>
        </p>
        <p className={styles.description}>
          <Link href="/sample_ssr">Go to Sample Server Side Renderder page</Link>
        </p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const data = await fetchJobs(undefined, { page: 6 });

  if (!data) {
    return {
      notFound: true,
    }
  }

  const jobs: Job[] = data.results.map((result: any) => {
    return {
      id: result.id,
      title: result.title,
      url: result.url,
      slug: result.slug
    }
  })

  return {
    props: { jobs }, // will be passed to the page component as props
    revalidate: 30,
  }
}
